//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceQuoteClient.InsuranceQuoteServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsuredInfo", Namespace="http://schemas.datacontract.org/2004/07/InsuranceQuoteService")]
    [System.SerializableAttribute()]
    public partial class InsuredInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleMakeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleYearBuiltField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Age {
            get {
                return this.AgeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeField, value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleMake {
            get {
                return this.VehicleMakeField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleMakeField, value) != true)) {
                    this.VehicleMakeField = value;
                    this.RaisePropertyChanged("VehicleMake");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleYearBuilt {
            get {
                return this.VehicleYearBuiltField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleYearBuiltField, value) != true)) {
                    this.VehicleYearBuiltField = value;
                    this.RaisePropertyChanged("VehicleYearBuilt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsuranceQuoteInfo", Namespace="http://schemas.datacontract.org/2004/07/InsuranceQuoteService")]
    [System.SerializableAttribute()]
    public partial class InsuranceQuoteInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AgeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BaseAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CarAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MontlyTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AgeAmount {
            get {
                return this.AgeAmountField;
            }
            set {
                if ((this.AgeAmountField.Equals(value) != true)) {
                    this.AgeAmountField = value;
                    this.RaisePropertyChanged("AgeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BaseAmount {
            get {
                return this.BaseAmountField;
            }
            set {
                if ((this.BaseAmountField.Equals(value) != true)) {
                    this.BaseAmountField = value;
                    this.RaisePropertyChanged("BaseAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CarAmount {
            get {
                return this.CarAmountField;
            }
            set {
                if ((this.CarAmountField.Equals(value) != true)) {
                    this.CarAmountField = value;
                    this.RaisePropertyChanged("CarAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MontlyTotal {
            get {
                return this.MontlyTotalField;
            }
            set {
                if ((this.MontlyTotalField.Equals(value) != true)) {
                    this.MontlyTotalField = value;
                    this.RaisePropertyChanged("MontlyTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultInfo", Namespace="http://schemas.datacontract.org/2004/07/InsuranceQuoteService")]
    [System.SerializableAttribute()]
    public partial class FaultInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InsuranceQuoteServiceProxy.IInsuranceQuoteService")]
    public interface IInsuranceQuoteService {
        
        // CODEGEN: Generating message contract since the operation GetQuoteUsingMessageContract is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceQuoteService/GetQuoteUsingMessageContract", ReplyAction="http://tempuri.org/IInsuranceQuoteService/GetQuoteUsingMessageContractResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InsuranceQuoteClient.InsuranceQuoteServiceProxy.FaultInfo), Action="http://tempuri.org/IInsuranceQuoteService/GetQuoteUsingMessageContractFaultInfoFa" +
            "ult", Name="FaultInfo", Namespace="http://schemas.datacontract.org/2004/07/InsuranceQuoteService")]
        InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuranceQuoteResponseMessage GetQuoteUsingMessageContract(InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuranceQuoteRequestMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsuranceQuoteService/GetQuote", ReplyAction="http://tempuri.org/IInsuranceQuoteService/GetQuoteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InsuranceQuoteClient.InsuranceQuoteServiceProxy.FaultInfo), Action="http://tempuri.org/IInsuranceQuoteService/GetQuoteFaultInfoFault", Name="FaultInfo", Namespace="http://schemas.datacontract.org/2004/07/InsuranceQuoteService")]
        InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuranceQuoteInfo GetQuote(InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuredInfo insuredInformation);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsuranceQuoteRequestMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuredInfo InsuredInformation;
        
        public InsuranceQuoteRequestMessage() {
        }
        
        public InsuranceQuoteRequestMessage(InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuredInfo InsuredInformation) {
            this.InsuredInformation = InsuredInformation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsuranceQuoteResponseMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuranceQuoteInfo QuoteInformation;
        
        public InsuranceQuoteResponseMessage() {
        }
        
        public InsuranceQuoteResponseMessage(InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuranceQuoteInfo QuoteInformation) {
            this.QuoteInformation = QuoteInformation;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IInsuranceQuoteServiceChannel : InsuranceQuoteClient.InsuranceQuoteServiceProxy.IInsuranceQuoteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class InsuranceQuoteServiceClient : System.ServiceModel.ClientBase<InsuranceQuoteClient.InsuranceQuoteServiceProxy.IInsuranceQuoteService>, InsuranceQuoteClient.InsuranceQuoteServiceProxy.IInsuranceQuoteService {
        
        public InsuranceQuoteServiceClient() {
        }
        
        public InsuranceQuoteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InsuranceQuoteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsuranceQuoteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsuranceQuoteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuranceQuoteResponseMessage InsuranceQuoteClient.InsuranceQuoteServiceProxy.IInsuranceQuoteService.GetQuoteUsingMessageContract(InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuranceQuoteRequestMessage request) {
            return base.Channel.GetQuoteUsingMessageContract(request);
        }
        
        public InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuranceQuoteInfo GetQuoteUsingMessageContract(InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuredInfo InsuredInformation) {
            InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuranceQuoteRequestMessage inValue = new InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuranceQuoteRequestMessage();
            inValue.InsuredInformation = InsuredInformation;
            InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuranceQuoteResponseMessage retVal = ((InsuranceQuoteClient.InsuranceQuoteServiceProxy.IInsuranceQuoteService)(this)).GetQuoteUsingMessageContract(inValue);
            return retVal.QuoteInformation;
        }
        
        public InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuranceQuoteInfo GetQuote(InsuranceQuoteClient.InsuranceQuoteServiceProxy.InsuredInfo insuredInformation) {
            return base.Channel.GetQuote(insuredInformation);
        }
    }
}
