//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 11/04/2010 1:07:55 PM
namespace TechSupportData
{
    
    /// <summary>
    /// There are no comments for Entities in the schema.
    /// </summary>
    public partial class Entities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : 
                base("name=Entities", "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : 
                base(connectionString, "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "Entities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for EFTechnicians in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<EFTechnician> EFTechnicians
        {
            get
            {
                if ((this._EFTechnicians == null))
                {
                    this._EFTechnicians = base.CreateQuery<EFTechnician>("[EFTechnicians]");
                }
                return this._EFTechnicians;
            }
        }
        private global::System.Data.Objects.ObjectQuery<EFTechnician> _EFTechnicians;
        /// <summary>
        /// There are no comments for EFTechnicians in the schema.
        /// </summary>
        public void AddToEFTechnicians(EFTechnician eFTechnician)
        {
            base.AddObject("EFTechnicians", eFTechnician);
        }
    }
    /// <summary>
    /// There are no comments for TechSupportModel.EFTechnician in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TechID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TechSupportModel", Name="EFTechnician")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EFTechnician : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new EFTechnician object.
        /// </summary>
        /// <param name="techID">Initial value of TechID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="email">Initial value of Email.</param>
        /// <param name="phone">Initial value of Phone.</param>
        public static EFTechnician CreateEFTechnician(int techID, string name, string email, string phone)
        {
            EFTechnician eFTechnician = new EFTechnician();
            eFTechnician.TechID = techID;
            eFTechnician.Name = name;
            eFTechnician.Email = email;
            eFTechnician.Phone = phone;
            return eFTechnician;
        }
        /// <summary>
        /// There are no comments for Property TechID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int TechID
        {
            get
            {
                return this._TechID;
            }
            set
            {
                this.OnTechIDChanging(value);
                this.ReportPropertyChanging("TechID");
                this._TechID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TechID");
                this.OnTechIDChanged();
            }
        }
        private int _TechID;
        partial void OnTechIDChanging(int value);
        partial void OnTechIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this.ReportPropertyChanging("Phone");
                this._Phone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Phone");
                this.OnPhoneChanged();
            }
        }
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
    }
}
